# Generated by Django 4.2 on 2025-06-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoFijo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=255, verbose_name='Funcion')),
                ('valorInicial', models.CharField(max_length=255, verbose_name='ValorInicial')),
                ('pricision', models.CharField(max_length=255, verbose_name='Precicion')),
                ('decimales', models.CharField(max_length=255, verbose_name='Decimales')),
            ],
        ),
    ]
