# Generated by Django 4.2 on 2025-06-22 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntofijo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='puntofijo',
            name='valorInicial',
            field=models.CharField(max_length=255, verbose_name='Valor Inicial'),
        ),
    ]
