# Generated by Django 4.2 on 2025-06-22 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculadora', '0002_puntofijo_creado_alter_puntofijo_valorinicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPuntoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=100)),
                ('x0', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('max_iter', models.IntegerField()),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('iteraciones', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PuntoFijo',
        ),
    ]
