# Generated by Django 4.2 on 2025-06-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_historialpuntofijo_delete_puntofijo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorialPuntoFijo',
        ),
    ]
