# Generated by Django 4.2 on 2025-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculadora', '0004_delete_historialpuntofijo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.TextField()),
                ('x_valor', models.FloatField()),
                ('resultado', models.FloatField()),
                ('razonamiento', models.TextField()),
                ('polinomio_usado', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
