# Generated by Django 4.2 on 2025-06-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoFijoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.TextField()),
                ('despeje', models.TextField()),
                ('valor_inicial', models.FloatField()),
                ('tolerancia', models.FloatField()),
                ('decimales', models.IntegerField()),
                ('solucion', models.FloatField()),
                ('error', models.FloatField()),
                ('comprobacion', models.TextField()),
                ('iteraciones', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
