# Generated by Django 4.2 on 2025-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='carnet',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='carrera',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ciclo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
