# Generated by Django 5.2.2 on 2025-06-29 06:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0011_userprofile_carnet_userprofile_carrera_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoGraficoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('funcion', models.CharField(max_length=255)),
                ('optimizacion', models.CharField(max_length=10)),
                ('restricciones', models.TextField()),
                ('solucion', models.CharField(max_length=100)),
                ('punto_optimo', models.CharField(max_length=100)),
                ('puntos_factibles', models.TextField()),
                ('vertices', models.TextField(blank=True, null=True)),
                ('iteraciones', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Método Gráfico',
                'verbose_name_plural': 'Historial Método Gráfico',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
