# Generated by Django 5.2.2 on 2025-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0012_metodograficohistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodograficohistorial',
            name='grafica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
