# Generated by Django 4.2 on 2025-07-01 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0012_simplexhistorial'),
        ('calculadora', '0013_metodograficohistorial_grafica'),
    ]

    operations = [
    ]
