# Generated by Django 4.2 on 2025-07-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0015_granmhistorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='idioma_preferido',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2),
        ),
    ]
